language: node_js
node_js:
  - 0.10
install:
  - npm install --global versal-sdk
  - npm install --global bower
  - npm install --global jshint
  - npm install --global nightwatch
before_script:
  - npm install
before_install:
  - mkdir -p tests/demos/lib
  - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar -O tests/demos/lib/selenium-server-standalone-2.44.0.jar
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
