language: node_js
node_js:
- 0.1
install:
- npm install --global git://github.com/Versal/sdk.git#fix/dist-dir-error
- npm install --global bower
- npm install --global jshint
- npm install --global nightwatch
before_script:
- sed -i s/BROWSERSTACK_USER/$BROWSERSTACK_USER/g nightwatch.travis.json
- sed -i s/BROWSERSTACK_KEY/$BROWSERSTACK_KEY/g nightwatch.travis.json
- cat nightwatch.travis.json
- curl -o BrowserStackTunnel.jar http://www.browserstack.com/BrowserStackTunnel.jar
- versal preview --port 3000 & && sleep 5 && java -jar BrowserStackTunnel.jar BROWSERSTACK_KEY localhost,3000,0 & && sleep 5
- npm install
script: nightwatch --config nightwatch.travis.json
env:
  global:
  - secure: HZ6MkAoq0vVOQLzWuHS5Cnr6vMx/wmxJR4LsWlv4gTSyCpTtgBBJgt+ZE+pSNi0RQeJ1JwlQbFslHBwrixavQuCfLOjlLBNnW9JAn2Z8jbPM5RZRFmDjYnL+4xGXZsobXhM5zGAEsNdX7TF2N3V1/xc7gGdy4Zj+aAYq8LMzTuw=
  - secure: kRYwz2COHZL0+pDL1EfG3oe7JcCBX8RgzHUxt9obqb1OsIbohsV9hPOltya98hiySbuNkml89Tlbp6bYPriYfl9OHpff6ptuuj2f0XViXg+1bLuczt11GkApdxfVVUDaXRxDoBvHz8Cs7SxRabHeUttAfur370rcP4oso8Portw=
