language: node_js
node_js:
  - 0.10
install:
  - npm install --global bower
  - npm install --global jshint
before_script:
  - npm install
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
